import {
  ProductCategory,
  Product,
  Customer,
  Supplier,
  Expense,
  UserProfile,
  BusinessSettings,
  Sale,
  Purchase,
  AuditLog,
  InventoryMovement,
  CustomerPayment,
} from '../types';

export const INITIAL_SETTINGS: BusinessSettings = {
  shop_name: 'Pasture Feeds & Farm Inputs',
  tagline: 'Quality Animal Feeds & Agricultural Inputs',
  phone: '+254 712 345 678',
  email: 'info@pasturefeeds.co.ke',
  location: 'Nakuru Town / Commercial Street',
  address: 'P.O. Box 4500-20100, Nakuru, Kenya',
  receipt_footer: 'Asante kwa Kununua Nasi! Karibu Tena.',
  currency: 'KES',
  currency_symbol: 'KSh',
  default_min_stock_bags: 5,
  allow_negative_stock: false,
  tax_enabled: false,
  tax_rate: 0,
};

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'u-admin-1',
    name: 'Edward Kimani (Owner)',
    email: 'edward@feeds.co.ke',
    role: 'ADMIN',
    phone: '+254 712 345 678',
    active: true,
  },
  {
    id: 'u-mgr-1',
    name: 'Faith Chebet (Store Manager)',
    email: 'faith@feeds.co.ke',
    role: 'MANAGER',
    phone: '+254 723 456 789',
    active: true,
  },
  {
    id: 'u-cashier-1',
    name: 'David Ochieng (Cashier)',
    email: 'david@feeds.co.ke',
    role: 'STAFF',
    phone: '+254 734 567 890',
    active: true,
  },
];

export const INITIAL_CATEGORIES: ProductCategory[] = [
  {
    id: 'cat-pig',
    name: 'Pig Products',
    slug: 'pig-products',
    description: 'Breeding, growing and lactating rations for commercial swine',
    color: '#ec4899',
    active: true,
  },
  {
    id: 'cat-cow',
    name: 'Cow Products',
    slug: 'cow-products',
    description: 'Dairy meals, calf feeds, heifer feeds and beef finishers',
    color: '#3b82f6',
    active: true,
  },
  {
    id: 'cat-poultry',
    name: 'Poultry Feeds',
    slug: 'poultry-feeds',
    description: 'Chick mash, duck mash, layers, growers and kienyeji feeds',
    color: '#eab308',
    active: true,
  },
  {
    id: 'cat-other-animal',
    name: 'Other Animal Feeds',
    slug: 'other-animal-feeds',
    description: 'Goat feeds, dog meals and rabbit rations',
    color: '#8b5cf6',
    active: true,
  },
  {
    id: 'cat-raw-materials',
    name: 'Raw Materials & Minerals',
    slug: 'raw-materials',
    description: 'Maize germ, pollard, bran, sunflower, soya and cattle minerals',
    color: '#10b981',
    active: true,
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Pasture Feeds Kenya Ltd',
    contact_person: 'Bernard Kariuki',
    phone: '+254 722 112 233',
    email: 'orders@pasturefeeds.co.ke',
    location: 'Industrial Area, Nakuru',
    notes: 'Primary feed manufacturer. Delivers Tuesdays and Fridays.',
    active: true,
    total_purchases_amount: 345000,
    created_at: '2026-01-10T08:00:00.000Z',
  },
  {
    id: 'sup-2',
    name: 'Unga Farm Care East Africa',
    contact_person: 'Mercy Wanjiru',
    phone: '+254 733 445 566',
    email: 'supply@ungafarmcare.com',
    location: 'Commercial Street, Nairobi',
    notes: 'Supplies raw materials, sunflower cake, and mineral licks.',
    active: true,
    total_purchases_amount: 180000,
    created_at: '2026-02-01T09:00:00.000Z',
  },
  {
    id: 'sup-3',
    name: 'Rift Millers & Grain Processors',
    contact_person: 'Peter Koech',
    phone: '+254 710 998 877',
    email: 'sales@riftmillers.co.ke',
    location: 'Eldoret Depot',
    notes: 'Maize germ, wheat bran and wheat pollard bulk supplier.',
    active: true,
    total_purchases_amount: 215000,
    created_at: '2026-02-15T11:00:00.000Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'John Karanja (Karanja Dairy)',
    phone: '+254 721 889 900',
    location: 'Njoro / Rongai',
    notes: 'Operates 25 pedigree cows. Buys 15 bags Dairy Meal monthly.',
    total_spent: 85200,
    total_orders: 8,
    last_purchase_date: '2026-09-02T14:30:00.000Z',
    created_at: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 'cust-2',
    name: 'Mama Mary Poultry Farm',
    phone: '+254 724 556 677',
    location: 'Bahati, Nakuru',
    notes: '1,500 layers flock. Regularly buys 50KG Layers Mash and Kienyeji.',
    total_spent: 64800,
    total_orders: 6,
    last_purchase_date: '2026-09-03T11:15:00.000Z',
    created_at: '2026-03-12T14:00:00.000Z',
  },
  {
    id: 'cust-3',
    name: 'Naivasha Piggeries Ltd',
    phone: '+254 735 667 788',
    location: 'Morendat, Naivasha',
    notes: 'Commercial pig breeding farm. Purchases Sow & Weaner, Pig Starter.',
    total_spent: 98400,
    total_orders: 9,
    last_purchase_date: '2026-09-01T09:45:00.000Z',
    created_at: '2026-04-05T08:30:00.000Z',
  },
  {
    id: 'cust-4',
    name: 'Stephen Kiprop',
    phone: '+254 718 223 344',
    location: 'Lanet',
    notes: 'Smallholder dairy farmer. Frequent walk-in customer.',
    total_spent: 18400,
    total_orders: 3,
    last_purchase_date: '2026-08-28T16:20:00.000Z',
    created_at: '2026-05-18T13:00:00.000Z',
  },
];

/**
 * Initial Products with Pasture Feeds price list dated 07/07/2025
 */
export const INITIAL_PRODUCTS: Product[] = [
  // 1. PIG PRODUCTS
  {
    id: 'prod-pig-sow-weaner',
    sku: 'PIG-SW-001',
    name: 'Sow & Weaner',
    category_id: 'cat-pig',
    subcategory: 'Swine Feed',
    brand: 'Pasture Feeds',
    description: 'Formulated for breeding sows and piglets during the weaning period.',
    base_unit: 'KG',
    selling_price_per_base_unit: 45,
    cost_price_per_base_unit: 36,
    min_stock_level: 250, // 5 bags of 50kg
    current_stock: 650, // 13 bags of 50kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-sw-50',
        product_id: 'prod-pig-sow-weaner',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2100,
        cost_price: 1800,
        barcode: '2001005001',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-sw-70',
        product_id: 'prod-pig-sow-weaner',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 2940,
        cost_price: 2520,
        barcode: '2001007001',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-sw-1',
        product_id: 'prod-pig-sow-weaner',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 45,
        cost_price: 36,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-pig-starter',
    sku: 'PIG-ST-002',
    name: 'Pig Starter',
    category_id: 'cat-pig',
    subcategory: 'Swine Feed',
    brand: 'Pasture Feeds',
    description: 'High-protein diet for early piglet development up to 25kg liveweight.',
    base_unit: 'KG',
    selling_price_per_base_unit: 55,
    cost_price_per_base_unit: 44,
    min_stock_level: 250,
    current_stock: 400, // 8 bags of 50kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-pst-50',
        product_id: 'prod-pig-starter',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2600,
        cost_price: 2200,
        barcode: '2001005002',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-pst-70',
        product_id: 'prod-pig-starter',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3640,
        cost_price: 3080,
        barcode: '2001007002',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pst-1',
        product_id: 'prod-pig-starter',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 55,
        cost_price: 44,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-pig-grower',
    sku: 'PIG-GR-003',
    name: 'Pig Grower',
    category_id: 'cat-pig',
    subcategory: 'Swine Feed',
    brand: 'Pasture Feeds',
    description: 'Nutrient-rich feed for fattening growers from 25kg to market weight.',
    base_unit: 'KG',
    selling_price_per_base_unit: 60,
    cost_price_per_base_unit: 48,
    min_stock_level: 250,
    current_stock: 350, // 7 bags of 50kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-pgr-50',
        product_id: 'prod-pig-grower',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2700,
        cost_price: 2300,
        barcode: '2001005003',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-pgr-70',
        product_id: 'prod-pig-grower',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3780,
        cost_price: 3200,
        barcode: '2001007003',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pgr-1',
        product_id: 'prod-pig-grower',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 60,
        cost_price: 48,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-pig-lactator',
    sku: 'PIG-LC-004',
    name: 'Lactator',
    category_id: 'cat-pig',
    subcategory: 'Swine Feed',
    brand: 'Pasture Feeds',
    description: 'Specialized lactation feed to boost milk production in nursing sows.',
    base_unit: 'KG',
    selling_price_per_base_unit: 60,
    cost_price_per_base_unit: 48,
    min_stock_level: 150,
    current_stock: 125, // Low stock alert! (2.5 bags)
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-plc-50',
        product_id: 'prod-pig-lactator',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2700,
        cost_price: 2300,
        barcode: '2001005004',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-plc-70',
        product_id: 'prod-pig-lactator',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3780,
        cost_price: 3200,
        barcode: '2001007004',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-plc-1',
        product_id: 'prod-pig-lactator',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 60,
        cost_price: 48,
        is_default: false,
        active: true,
      },
    ],
  },

  // 2. COW PRODUCTS
  {
    id: 'prod-cow-dairy-std',
    sku: 'COW-DM-001',
    name: 'Dairy Meal Standard',
    category_id: 'cat-cow',
    subcategory: 'Dairy Feeds',
    brand: 'Pasture Feeds',
    description: 'Balanced dairy ration for medium to high milk producing cows.',
    base_unit: 'KG',
    selling_price_per_base_unit: 43,
    cost_price_per_base_unit: 34,
    min_stock_level: 350,
    current_stock: 850, // 17 bags of 50kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-dms-70',
        product_id: 'prod-cow-dairy-std',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 2900,
        cost_price: 2450,
        barcode: '2002007001',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-dms-50',
        product_id: 'prod-cow-dairy-std',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2100,
        cost_price: 1750,
        barcode: '2002005001',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-dms-1',
        product_id: 'prod-cow-dairy-std',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 43,
        cost_price: 34,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-cow-dairy-highyield',
    sku: 'COW-DM-002',
    name: 'Dairy Meal Highyield',
    category_id: 'cat-cow',
    subcategory: 'Dairy Feeds',
    brand: 'Pasture Feeds',
    description: 'Premium bypass protein dairy meal for cows producing over 20 litres daily.',
    base_unit: 'KG',
    selling_price_per_base_unit: 45,
    cost_price_per_base_unit: 36,
    min_stock_level: 350,
    current_stock: 720,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-dmh-70',
        product_id: 'prod-cow-dairy-highyield',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3050,
        cost_price: 2550,
        barcode: '2002007002',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-dmh-50',
        product_id: 'prod-cow-dairy-highyield',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2200,
        cost_price: 1850,
        barcode: '2002005002',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-dmh-1',
        product_id: 'prod-cow-dairy-highyield',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 45,
        cost_price: 36,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-cow-beef-finisher',
    sku: 'COW-BF-003',
    name: 'Beef Finisher',
    category_id: 'cat-cow',
    subcategory: 'Beef Cattle',
    brand: 'Pasture Feeds',
    description: 'High energy finishing ration for rapid carcass weight gain.',
    base_unit: 'KG',
    selling_price_per_base_unit: 43,
    cost_price_per_base_unit: 35,
    min_stock_level: 200,
    current_stock: 450,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-cbf-70',
        product_id: 'prod-cow-beef-finisher',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 2900,
        cost_price: 2450,
        barcode: '2002007003',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-cbf-50',
        product_id: 'prod-cow-beef-finisher',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2100,
        cost_price: 1750,
        barcode: '2002005003',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-cbf-1',
        product_id: 'prod-cow-beef-finisher',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 43,
        cost_price: 35,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-cow-calf-feeds',
    sku: 'COW-CF-004',
    name: 'Calf Feeds',
    category_id: 'cat-cow',
    subcategory: 'Young Stock',
    brand: 'Pasture Feeds',
    description: 'Early rumen development starter pellets and mash for calves.',
    base_unit: 'KG',
    selling_price_per_base_unit: 43,
    cost_price_per_base_unit: 35,
    min_stock_level: 200,
    current_stock: 350,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-ccf-70',
        product_id: 'prod-cow-calf-feeds',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 2900,
        cost_price: 2450,
        barcode: '2002007004',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-ccf-50',
        product_id: 'prod-cow-calf-feeds',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2100,
        cost_price: 1750,
        barcode: '2002005004',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-ccf-1',
        product_id: 'prod-cow-calf-feeds',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 43,
        cost_price: 35,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-cow-heifer',
    sku: 'COW-HF-005',
    name: 'Heifer',
    category_id: 'cat-cow',
    subcategory: 'Young Stock',
    brand: 'Pasture Feeds',
    description: 'Nutritional ration designed for growing replacement heifers.',
    base_unit: 'KG',
    selling_price_per_base_unit: 43,
    cost_price_per_base_unit: 35,
    min_stock_level: 200,
    current_stock: 420,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-chf-70',
        product_id: 'prod-cow-heifer',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 2900,
        cost_price: 2450,
        barcode: '2002007005',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-chf-50',
        product_id: 'prod-cow-heifer',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2100,
        cost_price: 1750,
        barcode: '2002005005',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-chf-1',
        product_id: 'prod-cow-heifer',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 43,
        cost_price: 35,
        is_default: false,
        active: true,
      },
    ],
  },

  // 3. POULTRY FEEDS
  {
    id: 'prod-poul-chick-duck',
    sku: 'POUL-CD-001',
    name: 'Chick & Duck Mash',
    category_id: 'cat-poultry',
    subcategory: 'Brooding Feeds',
    brand: 'Pasture Feeds',
    description: 'Complete balanced mash with coccidiostat for day-old chicks and ducklings.',
    base_unit: 'KG',
    selling_price_per_base_unit: 60,
    cost_price_per_base_unit: 48,
    min_stock_level: 300,
    current_stock: 500,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-pcd-70',
        product_id: 'prod-poul-chick-duck',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3920,
        cost_price: 3300,
        barcode: '2003007001',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pcd-50',
        product_id: 'prod-poul-chick-duck',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2800,
        cost_price: 2350,
        barcode: '2003005001',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-pcd-20',
        product_id: 'prod-poul-chick-duck',
        package_name: '20 KG Bag',
        size_in_base_units: 20,
        selling_price: 1120,
        cost_price: 940,
        barcode: '2003002001',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pcd-10',
        product_id: 'prod-poul-chick-duck',
        package_name: '10 KG Bag',
        size_in_base_units: 10,
        selling_price: 560,
        cost_price: 470,
        barcode: '2003001001',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pcd-1',
        product_id: 'prod-poul-chick-duck',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 60,
        cost_price: 48,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-poul-layers-mash',
    sku: 'POUL-LM-002',
    name: 'Layers Mash',
    category_id: 'cat-poultry',
    subcategory: 'Egg Production',
    brand: 'Pasture Feeds',
    description: 'High calcium and methionine formula for peak egg yield and hard eggshells.',
    base_unit: 'KG',
    selling_price_per_base_unit: 55,
    cost_price_per_base_unit: 44,
    min_stock_level: 400,
    current_stock: 950, // 19 bags of 50kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-plm-70',
        product_id: 'prod-poul-layers-mash',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3780,
        cost_price: 3150,
        barcode: '2003007002',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-plm-50',
        product_id: 'prod-poul-layers-mash',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2700,
        cost_price: 2250,
        barcode: '2003005002',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-plm-20',
        product_id: 'prod-poul-layers-mash',
        package_name: '20 KG Bag',
        size_in_base_units: 20,
        selling_price: 1080,
        cost_price: 900,
        barcode: '2003002002',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-plm-10',
        product_id: 'prod-poul-layers-mash',
        package_name: '10 KG Bag',
        size_in_base_units: 10,
        selling_price: 540,
        cost_price: 450,
        barcode: '2003001002',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-plm-1',
        product_id: 'prod-poul-layers-mash',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 55,
        cost_price: 44,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-poul-growers-mash',
    sku: 'POUL-GM-003',
    name: 'Growers Mash',
    category_id: 'cat-poultry',
    subcategory: 'Pullet Feeds',
    brand: 'Pasture Feeds',
    description: 'Balanced grower mash fed from 8 weeks to point of lay.',
    base_unit: 'KG',
    selling_price_per_base_unit: 50,
    cost_price_per_base_unit: 40,
    min_stock_level: 300,
    current_stock: 450,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-pgm-70',
        product_id: 'prod-poul-growers-mash',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3500,
        cost_price: 2900,
        barcode: '2003007003',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pgm-50',
        product_id: 'prod-poul-growers-mash',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2500,
        cost_price: 2080,
        barcode: '2003005003',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-pgm-20',
        product_id: 'prod-poul-growers-mash',
        package_name: '20 KG Bag',
        size_in_base_units: 20,
        selling_price: 1000,
        cost_price: 830,
        barcode: '2003002003',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pgm-10',
        product_id: 'prod-poul-growers-mash',
        package_name: '10 KG Bag',
        size_in_base_units: 10,
        selling_price: 500,
        cost_price: 415,
        barcode: '2003001003',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pgm-1',
        product_id: 'prod-poul-growers-mash',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 50,
        cost_price: 40,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-poul-kienyeji-mash',
    sku: 'POUL-KM-004',
    name: 'Kienyeji Mash',
    category_id: 'cat-poultry',
    subcategory: 'Indigenous & Improved Feeds',
    brand: 'Pasture Feeds',
    description: 'Tailored for indigenous, Kuroiler, Rainbow Rooster, and Sasso chickens.',
    base_unit: 'KG',
    selling_price_per_base_unit: 55,
    cost_price_per_base_unit: 44,
    min_stock_level: 300,
    current_stock: 580,
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-pkm-70',
        product_id: 'prod-poul-kienyeji-mash',
        package_name: '70 KG Bag',
        size_in_base_units: 70,
        selling_price: 3640,
        cost_price: 3050,
        barcode: '2003007004',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pkm-50',
        product_id: 'prod-poul-kienyeji-mash',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2600,
        cost_price: 2180,
        barcode: '2003005004',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-pkm-20',
        product_id: 'prod-poul-kienyeji-mash',
        package_name: '20 KG Bag',
        size_in_base_units: 20,
        selling_price: 1040,
        cost_price: 870,
        barcode: '2003002004',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pkm-10',
        product_id: 'prod-poul-kienyeji-mash',
        package_name: '10 KG Bag',
        size_in_base_units: 10,
        selling_price: 520,
        cost_price: 435,
        barcode: '2003001004',
        is_default: false,
        active: true,
      },
      {
        id: 'pkg-pkm-1',
        product_id: 'prod-poul-kienyeji-mash',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 55,
        cost_price: 44,
        is_default: false,
        active: true,
      },
    ],
  },

  // 4. OTHER ANIMAL FEEDS
  {
    id: 'prod-other-goat-feeds',
    sku: 'OTH-GT-001',
    name: 'Goat Feeds',
    category_id: 'cat-other-animal',
    subcategory: 'Dairy Goat',
    brand: 'Pasture Feeds',
    description: 'Dairy goat supplement pellets for milk production and twin-rearing does.',
    base_unit: 'KG',
    selling_price_per_base_unit: 45,
    cost_price_per_base_unit: 36,
    min_stock_level: 100,
    current_stock: 160, // 8 bags of 20kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-ogt-20',
        product_id: 'prod-other-goat-feeds',
        package_name: '20 KG Bag',
        size_in_base_units: 20,
        selling_price: 900,
        cost_price: 720,
        barcode: '2004002001',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-ogt-1',
        product_id: 'prod-other-goat-feeds',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 45,
        cost_price: 36,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-other-dog-feeds',
    sku: 'OTH-DG-002',
    name: 'Dog Feeds',
    category_id: 'cat-other-animal',
    subcategory: 'Canine Feeds',
    brand: 'Pasture Feeds',
    description: 'Complete nutritional dry dog kibble for active working and guard dogs.',
    base_unit: 'KG',
    selling_price_per_base_unit: 55,
    cost_price_per_base_unit: 44,
    min_stock_level: 50,
    current_stock: 90, // 9 bags of 10kg
    supplier_id: 'sup-1',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-odg-10',
        product_id: 'prod-other-dog-feeds',
        package_name: '10 KG Bag',
        size_in_base_units: 10,
        selling_price: 550,
        cost_price: 440,
        barcode: '2004001001',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-odg-1',
        product_id: 'prod-other-dog-feeds',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 55,
        cost_price: 44,
        is_default: false,
        active: true,
      },
    ],
  },

  // 5. RAW MATERIALS
  {
    id: 'prod-raw-maize-germ',
    sku: 'RAW-MG-001',
    name: 'Maize Germ',
    category_id: 'cat-raw-materials',
    subcategory: 'Energy Ingredients',
    brand: 'Rift Millers',
    description: 'Clean energy-dense milled maize germ for home mixing and formulation.',
    base_unit: 'KG',
    selling_price_per_base_unit: 45,
    cost_price_per_base_unit: 36,
    min_stock_level: 250,
    current_stock: 750, // 15 bags of 50kg
    supplier_id: 'sup-3',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rmg-50',
        product_id: 'prod-raw-maize-germ',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2100,
        cost_price: 1800,
        barcode: '2005005001',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-rmg-1',
        product_id: 'prod-raw-maize-germ',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 45,
        cost_price: 36,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-wheat-pollard',
    sku: 'RAW-WP-002',
    name: 'Wheat Pollard',
    category_id: 'cat-raw-materials',
    subcategory: 'Cereal By-Products',
    brand: 'Rift Millers',
    description: 'High-energy wheat pollard ideal for ruminant and swine diets.',
    base_unit: 'KG',
    selling_price_per_base_unit: 40,
    cost_price_per_base_unit: 32,
    min_stock_level: 250,
    current_stock: 600,
    supplier_id: 'sup-3',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rwp-50',
        product_id: 'prod-raw-wheat-pollard',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 2000,
        cost_price: 1600,
        barcode: '2005005002',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-rwp-1',
        product_id: 'prod-raw-wheat-pollard',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 40,
        cost_price: 32,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-wheat-bran',
    sku: 'RAW-WB-003',
    name: 'Wheat Bran',
    category_id: 'cat-raw-materials',
    subcategory: 'Cereal By-Products',
    brand: 'Rift Millers',
    description: 'Fluffy fibre source to aid digestion and rumen motility in dairy cows.',
    base_unit: 'KG',
    selling_price_per_base_unit: 30,
    cost_price_per_base_unit: 22,
    min_stock_level: 200,
    current_stock: 480, // 12 bags of 40kg
    supplier_id: 'sup-3',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rwb-40',
        product_id: 'prod-raw-wheat-bran',
        package_name: '40 KG Bag',
        size_in_base_units: 40,
        selling_price: 1120,
        cost_price: 880,
        barcode: '2005004003',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-rwb-1',
        product_id: 'prod-raw-wheat-bran',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 30,
        cost_price: 22,
        is_default: false,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-sunflower',
    sku: 'RAW-SF-004',
    name: 'Sunflower',
    category_id: 'cat-raw-materials',
    subcategory: 'Oil Seed Meals',
    brand: 'Unga Farm Care',
    description: 'Crushed sunflower seed cake for high protein and essential fatty acids.',
    base_unit: 'KG',
    selling_price_per_base_unit: 55,
    cost_price_per_base_unit: 45,
    min_stock_level: 100,
    current_stock: 320,
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rsf-1',
        product_id: 'prod-raw-sunflower',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 55,
        cost_price: 45,
        barcode: '2005001004',
        is_default: true,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-cotton-cake',
    sku: 'RAW-CC-005',
    name: 'Cotton Cake',
    category_id: 'cat-raw-materials',
    subcategory: 'Oil Seed Meals',
    brand: 'Unga Farm Care',
    description: 'High-protein expeller pressed cotton seed cake for cattle feeds.',
    base_unit: 'KG',
    selling_price_per_base_unit: 65,
    cost_price_per_base_unit: 52,
    min_stock_level: 100,
    current_stock: 280,
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rcc-1',
        product_id: 'prod-raw-cotton-cake',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 65,
        cost_price: 52,
        barcode: '2005001005',
        is_default: true,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-soya',
    sku: 'RAW-SY-006',
    name: 'Soya',
    category_id: 'cat-raw-materials',
    subcategory: 'Plant Proteins',
    brand: 'Unga Farm Care',
    description: 'Extruded full-fat roasted soya meal with exceptional lysine content.',
    base_unit: 'KG',
    selling_price_per_base_unit: 130,
    cost_price_per_base_unit: 108,
    min_stock_level: 100,
    current_stock: 190,
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rsy-1',
        product_id: 'prod-raw-soya',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 130,
        cost_price: 108,
        barcode: '2005001006',
        is_default: true,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-ochonga',
    sku: 'RAW-OC-007',
    name: 'Ochonga',
    category_id: 'cat-raw-materials',
    subcategory: 'Marine Proteins',
    brand: 'Lake Victoria Catch',
    description: 'Sun-dried freshwater shrimp meal (Ochonga) rich in organic minerals and protein.',
    base_unit: 'KG',
    selling_price_per_base_unit: 75,
    cost_price_per_base_unit: 60,
    min_stock_level: 80,
    current_stock: 150,
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-roc-1',
        product_id: 'prod-raw-ochonga',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 75,
        cost_price: 60,
        barcode: '2005001007',
        is_default: true,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-fish-meal',
    sku: 'RAW-FM-008',
    name: 'Fish Meal',
    category_id: 'cat-raw-materials',
    subcategory: 'Marine Proteins',
    brand: 'Lake Victoria Catch',
    description: '60% CP pure milled fish meal (Omena/Dagaa) for superior chick and pig starter.',
    base_unit: 'KG',
    selling_price_per_base_unit: 130,
    cost_price_per_base_unit: 105,
    min_stock_level: 80,
    current_stock: 110,
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rfm-1',
        product_id: 'prod-raw-fish-meal',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 130,
        cost_price: 105,
        barcode: '2005001008',
        is_default: true,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-cattle-salt',
    sku: 'RAW-CS-009',
    name: 'Cattle Salt',
    category_id: 'cat-raw-materials',
    subcategory: 'Minerals',
    brand: 'Magadi Salt',
    description: 'Coarse mineralized sodium chloride for livestock supplementation.',
    base_unit: 'KG',
    selling_price_per_base_unit: 20,
    cost_price_per_base_unit: 14,
    min_stock_level: 150,
    current_stock: 450,
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rcs-1',
        product_id: 'prod-raw-cattle-salt',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 20,
        cost_price: 14,
        barcode: '2005001009',
        is_default: true,
        active: true,
      },
    ],
  },
  {
    id: 'prod-raw-lime',
    sku: 'RAW-LM-010',
    name: 'Lime',
    category_id: 'cat-raw-materials',
    subcategory: 'Minerals',
    brand: 'Athi River Lime',
    description: 'Agricultural feed-grade calcium carbonate for bone and eggshell strength.',
    base_unit: 'KG',
    selling_price_per_base_unit: 10,
    cost_price_per_base_unit: 7,
    min_stock_level: 250,
    current_stock: 650, // 13 bags of 50kg
    supplier_id: 'sup-2',
    active: true,
    created_at: '2026-07-07T08:00:00.000Z',
    updated_at: '2026-07-07T08:00:00.000Z',
    packages: [
      {
        id: 'pkg-rlm-50',
        product_id: 'prod-raw-lime',
        package_name: '50 KG Bag',
        size_in_base_units: 50,
        selling_price: 500,
        cost_price: 350,
        barcode: '2005005010',
        is_default: true,
        active: true,
      },
      {
        id: 'pkg-rlm-1',
        product_id: 'prod-raw-lime',
        package_name: '1 KG Loose',
        size_in_base_units: 1,
        selling_price: 10,
        cost_price: 7,
        is_default: false,
        active: true,
      },
    ],
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    category: 'Transport',
    description: 'Offloading 150 bags Pasture Feeds shipment at depot',
    amount: 3500,
    expense_date: '2026-09-02T10:00:00.000Z',
    created_by: 'Faith Chebet',
    notes: 'Paid casual workers in cash',
    created_at: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'exp-2',
    category: 'Rent',
    description: 'Monthly store premise rental (September 2026)',
    amount: 35000,
    expense_date: '2026-09-01T08:30:00.000Z',
    created_by: 'Edward Kimani',
    notes: 'Commercial shop lot #4',
    created_at: '2026-09-01T08:30:00.000Z',
  },
  {
    id: 'exp-3',
    category: 'Electricity',
    description: 'KPLC token for weighing scales, lights, ventilation',
    amount: 2800,
    expense_date: '2026-09-01T15:00:00.000Z',
    created_by: 'Edward Kimani',
    receipt_ref: 'ELEC-9021',
    created_at: '2026-09-01T15:00:00.000Z',
  },
  {
    id: 'exp-4',
    category: 'Packaging',
    description: '500 Heavy-gauge khaki and poly carrier bags for loose sales',
    amount: 4200,
    expense_date: '2026-08-28T11:20:00.000Z',
    created_by: 'David Ochieng',
    created_at: '2026-08-28T11:20:00.000Z',
  },
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale-1',
    receipt_number: 'INV-000120',
    customer_id: 'cust-1',
    customer_name: 'John Karanja (Karanja Dairy)',
    customer_phone: '+254 721 889 900',
    items: [
      {
        id: 'si-1',
        product_id: 'prod-cow-dairy-highyield',
        product_name: 'Dairy Meal Highyield',
        package_id: 'pkg-dmh-70',
        package_name: '70 KG Bag',
        quantity: 2,
        quantity_base_units: 140,
        unit_price: 3050,
        cost_price_per_unit: 2550,
        line_total: 6100,
        estimated_profit: 1000,
      },
      {
        id: 'si-2',
        product_id: 'prod-raw-cattle-salt',
        product_name: 'Cattle Salt',
        package_id: 'pkg-rcs-1',
        package_name: '1 KG Loose',
        quantity: 10,
        quantity_base_units: 10,
        unit_price: 20,
        cost_price_per_unit: 14,
        line_total: 200,
        estimated_profit: 60,
      },
    ],
    subtotal: 6300,
    discount: 0,
    total: 6300,
    payment_method: 'CASH',
    amount_paid: 6300,
    payment_status: 'PAID',
    status: 'COMPLETED',
    created_by: 'David Ochieng',
    created_at: '2026-09-03T10:15:00.000Z',
  },
  {
    id: 'sale-2',
    receipt_number: 'INV-000121',
    customer_id: 'cust-2',
    customer_name: 'Mama Mary Poultry Farm',
    customer_phone: '+254 724 556 677',
    items: [
      {
        id: 'si-3',
        product_id: 'prod-poul-layers-mash',
        product_name: 'Layers Mash',
        package_id: 'pkg-plm-50',
        package_name: '50 KG Bag',
        quantity: 3,
        quantity_base_units: 150,
        unit_price: 2700,
        cost_price_per_unit: 2250,
        line_total: 8100,
        estimated_profit: 1350,
      },
    ],
    subtotal: 8100,
    discount: 100,
    total: 8000,
    payment_method: 'CASH',
    amount_paid: 8000,
    payment_status: 'PAID',
    notes: 'Regular customer discount',
    status: 'COMPLETED',
    created_by: 'David Ochieng',
    created_at: '2026-09-03T11:45:00.000Z',
  },
  {
    id: 'sale-3',
    receipt_number: 'INV-000122',
    customer_name: 'Walk-in Customer',
    items: [
      {
        id: 'si-4',
        product_id: 'prod-pig-starter',
        product_name: 'Pig Starter',
        package_id: 'pkg-pst-1',
        package_name: '1 KG Loose',
        quantity: 7,
        quantity_base_units: 7,
        unit_price: 55,
        cost_price_per_unit: 44,
        line_total: 385,
        estimated_profit: 77,
      },
    ],
    subtotal: 385,
    discount: 0,
    total: 385,
    payment_method: 'CASH',
    amount_paid: 385,
    payment_status: 'PAID',
    status: 'COMPLETED',
    created_by: 'David Ochieng',
    created_at: '2026-09-03T14:20:00.000Z',
  },
  {
    id: 'sale-4',
    receipt_number: 'INV-000123',
    customer_id: 'cust-1',
    customer_name: 'John Karanja (Karanja Dairy)',
    customer_phone: '+254 721 889 900',
    items: [
      {
        id: 'si-5',
        product_id: 'prod-cow-dairy-highyield',
        product_name: 'Dairy Meal Highyield',
        package_id: 'pkg-dmh-70',
        package_name: '70 KG Bag',
        quantity: 2,
        quantity_base_units: 140,
        unit_price: 3050,
        cost_price_per_unit: 2550,
        line_total: 6100,
        estimated_profit: 1000,
      },
    ],
    subtotal: 6100,
    discount: 0,
    total: 6100,
    payment_method: 'ON_CREDIT',
    amount_paid: 0,
    payment_status: 'UNPAID',
    notes: 'Credit purchase for milking cows. Due end of week.',
    status: 'COMPLETED',
    created_by: 'David Ochieng',
    created_at: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'sale-5',
    receipt_number: 'INV-000124',
    customer_id: 'cust-3',
    customer_name: 'Peter Kiptoo (Kiptoo Pig Farm)',
    customer_phone: '+254 725 334 455',
    items: [
      {
        id: 'si-6',
        product_id: 'prod-pig-grower',
        product_name: 'Pig Grower Feed',
        package_id: 'pkg-pgr-50',
        package_name: '50 KG Bag',
        quantity: 2,
        quantity_base_units: 100,
        unit_price: 2500,
        cost_price_per_unit: 2100,
        line_total: 5000,
        estimated_profit: 800,
      },
      {
        id: 'si-7',
        product_id: 'prod-pig-finisher',
        product_name: 'Pig Finisher Meal',
        package_id: 'pkg-pfn-50',
        package_name: '50 KG Bag',
        quantity: 1,
        quantity_base_units: 50,
        unit_price: 2400,
        cost_price_per_unit: 2000,
        line_total: 2400,
        estimated_profit: 400,
      },
    ],
    subtotal: 7400,
    discount: 0,
    total: 7400,
    payment_method: 'ON_CREDIT',
    amount_paid: 2500,
    payment_status: 'PARTIAL',
    notes: 'Paid KSh 2,500 deposit; balance KSh 4,900 on store credit tab.',
    status: 'COMPLETED',
    created_by: 'Faith Chebet',
    created_at: '2026-09-01T14:30:00.000Z',
  },
];

export const INITIAL_CUSTOMER_PAYMENTS: CustomerPayment[] = [
  {
    id: 'pay-initial-1',
    payment_number: 'PAY-000100',
    customer_id: 'cust-3',
    customer_name: 'Peter Kiptoo (Kiptoo Pig Farm)',
    amount: 2500,
    payment_method: 'CASH',
    reference: 'CASH-DEP-01',
    notes: 'Initial deposit paid at time of ordering INV-000124',
    applied_sales: [
      {
        sale_id: 'sale-5',
        receipt_number: 'INV-000124',
        amount_applied: 2500,
      },
    ],
    created_by: 'Faith Chebet',
    created_at: '2026-09-01T14:30:00.000Z',
  },
];

export const INITIAL_PURCHASES: Purchase[] = [
  {
    id: 'po-1',
    invoice_number: 'PF-REC-9942',
    supplier_id: 'sup-1',
    supplier_name: 'Pasture Feeds Kenya Ltd',
    purchase_date: '2026-09-01T09:00:00.000Z',
    items: [
      {
        id: 'pi-1',
        product_id: 'prod-poul-layers-mash',
        product_name: 'Layers Mash',
        package_name: '50 KG Bag',
        quantity: 10,
        quantity_base_units: 500,
        cost_price: 2250,
        line_total: 22500,
      },
      {
        id: 'pi-2',
        product_id: 'prod-cow-dairy-std',
        product_name: 'Dairy Meal Standard',
        package_name: '70 KG Bag',
        quantity: 10,
        quantity_base_units: 700,
        cost_price: 2450,
        line_total: 24500,
      },
    ],
    total_cost: 47000,
    notes: 'Received in good condition. Stock added to warehouse.',
    created_by: 'Faith Chebet',
    created_at: '2026-09-01T09:00:00.000Z',
  },
];

export const INITIAL_MOVEMENTS: InventoryMovement[] = [
  {
    id: 'mov-1',
    product_id: 'prod-poul-layers-mash',
    product_name: 'Layers Mash',
    package_name: '50 KG Bag',
    quantity_packages: 10,
    quantity_base_units: 500,
    base_unit: 'KG',
    previous_stock: 600,
    new_stock: 1100,
    movement_type: 'PURCHASE',
    reference_number: 'PF-REC-9942',
    notes: 'Restock from Pasture Feeds',
    created_by: 'Faith Chebet',
    created_at: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'mov-2',
    product_id: 'prod-cow-dairy-highyield',
    product_name: 'Dairy Meal Highyield',
    package_name: '70 KG Bag',
    quantity_packages: 2,
    quantity_base_units: -140,
    base_unit: 'KG',
    previous_stock: 860,
    new_stock: 720,
    movement_type: 'SALE',
    reference_number: 'INV-000120',
    notes: 'Sale to John Karanja',
    created_by: 'David Ochieng',
    created_at: '2026-09-03T10:15:00.000Z',
  },
  {
    id: 'mov-3',
    product_id: 'prod-poul-layers-mash',
    product_name: 'Layers Mash',
    package_name: '50 KG Bag',
    quantity_packages: 3,
    quantity_base_units: -150,
    base_unit: 'KG',
    previous_stock: 1100,
    new_stock: 950,
    movement_type: 'SALE',
    reference_number: 'INV-000121',
    notes: 'Sale to Mama Mary Poultry',
    created_by: 'David Ochieng',
    created_at: '2026-09-03T11:45:00.000Z',
  },
  {
    id: 'mov-4',
    product_id: 'prod-pig-starter',
    product_name: 'Pig Starter',
    package_name: '1 KG Loose',
    quantity_packages: 7,
    quantity_base_units: -7,
    base_unit: 'KG',
    previous_stock: 407,
    new_stock: 400,
    movement_type: 'SALE',
    reference_number: 'INV-000122',
    notes: 'Loose feed sale',
    created_by: 'David Ochieng',
    created_at: '2026-09-03T14:20:00.000Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    user_name: 'Edward Kimani',
    user_role: 'ADMIN',
    action: 'SYSTEM_INIT',
    entity: 'System',
    details: 'Initial system setup with Pasture Feeds product catalog',
    created_at: '2026-07-07T08:00:00.000Z',
  },
  {
    id: 'log-2',
    user_name: 'Faith Chebet',
    user_role: 'MANAGER',
    action: 'PURCHASE_CREATED',
    entity: 'Purchase',
    entity_id: 'PF-REC-9942',
    details: 'Received purchase from Pasture Feeds Kenya Ltd (Total: KSh 47,000)',
    created_at: '2026-09-01T09:00:00.000Z',
  },
  {
    id: 'log-3',
    user_name: 'David Ochieng',
    user_role: 'STAFF',
    action: 'SALE_COMPLETED',
    entity: 'Sale',
    entity_id: 'INV-000120',
    details: 'Completed sale to John Karanja (Total: KSh 6,300)',
    created_at: '2026-09-03T10:15:00.000Z',
  },
];
